### ISSUE TITLE
Plugin does not support star property hack of IE7

### ISSUE THREAD

**Issue by philipjohn007** [gabrysbiz/css-splitter-maven-plugin#8]
I found the plugin very useful. But since our style sheets make use of the star hack of IE previous versions (like _*display: inline;_ ) to facilitate the application in all versions, when I run the plugin, it throws the following error

Error in declaration. '*' is not allowed as first char of a property.

Also when the following properties.
_filter: progid:dximagetransform.microsoft.gradient(enabled=false);_
throws the following error.
Error in expression; ':' found after identifier "progid".

**Comment by philipjohn007** [comment]
It also throws error when the CSS has Paged Media like 
 @page  {
    margin: 2cm;
  }

**Comment by agabrys** [comment]
Hi,
I use the latest stable version of the [CSS Parser](http://cssparser.sourceforge.net/) (0.9.18).
___

I didn't found any bugs related to ``*property-name``. Please create a ticket on [CSS Parser Issue Tracking System](https://sourceforge.net/p/cssparser/bugs/).
___

I found some bugs related with ``progId`` problems:
* [#46 colon in filter value leads to parsing error](https://sourceforge.net/p/cssparser/bugs/46/)
* [#49 CssParser not work with IE css](https://sourceforge.net/p/cssparser/bugs/49/)

You should try to use 0.9.19-SNAPSHOT (hosted on [oss.sonatype.org](https://oss.sonatype.org/content/repositories/snapshots/net/sourceforge/cssparser/cssparser/0.9.19-SNAPSHOT/)):

    <plugin>
        <groupId>biz.gabrys.maven.plugins</groupId>
        <artifactId>css-splitter-maven-plugin</artifactId>
        <version>1.0-SNAPSHOT</version>
        <dependencies>
            <dependency>
                <groupId>net.sourceforge.cssparser</groupId>
                <artifactId>cssparser</artifactId>
                <version>0.9.19-SNAPSHOT</version>
            </dependency>
        </dependencies>
    </plugin>

___

Please add stacktrace for ``@page`` rule.

**Comment by philipjohn007** [comment]
The stacktrace for `@page` is as follows.
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.gabrys.maven.plugins:css-splitter-maven-plugin:1.0-SNAPSHOT:split (default-split) on project ThemeSample: Rule represented by "com.steadystate.css.dom.CSSPageRuleImpl" class (type: 6) is unsupported! CSS code that causes error:
@page {margin: 2cm}
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Rule represented by "com.steadystate.css.dom.CSSPageRuleImpl" class (type: 6) is unsupported! CSS code that causes error:
@page {margin: 2cm}
        at biz.gabrys.maven.plugins.css.splitter.SplitMojo.splitFile(SplitMojo.java:358)
        at biz.gabrys.maven.plugins.css.splitter.SplitMojo.splitFiles(SplitMojo.java:325)
        at biz.gabrys.maven.plugins.css.splitter.SplitMojo.runSplitter(SplitMojo.java:307)
        at biz.gabrys.maven.plugins.css.splitter.SplitMojo.execute(SplitMojo.java:294)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: biz.gabrys.maven.plugins.css.splitter.steadystate.converters.UnsupportedRuleException: Rule represented by "com.steadystate.css.dom.CSSPageRuleImpl" class (type: 6) is unsupported! CSS code that causes error:
@page {margin: 2cm}
        at biz.gabrys.maven.plugins.css.splitter.steadystate.converters.AbstractRuleConverter.convert(AbstractRuleConverter.java:35)
        at biz.gabrys.maven.plugins.css.splitter.steadystate.converters.MediaRuleConverter.convert2(MediaRuleConverter.java:51)
        at biz.gabrys.maven.plugins.css.splitter.steadystate.converters.MediaRuleConverter.convert2(MediaRuleConverter.java:27)
        at biz.gabrys.maven.plugins.css.splitter.steadystate.converters.AbstractRuleConverter.convert(AbstractRuleConverter.java:37)
        at biz.gabrys.maven.plugins.css.splitter.steadystate.converters.ConverterUtils.convert(ConverterUtils.java:28)
        at biz.gabrys.maven.plugins.css.splitter.steadystate.converters.StyleSheetConverter.convert(StyleSheetConverter.java:48)
        at biz.gabrys.maven.plugins.css.splitter.steadystate.SteadyStateParser.parse(SteadyStateParser.java:53)
        at biz.gabrys.maven.plugins.css.splitter.SplitMojo.splitFile(SplitMojo.java:353)
        ... 25 more
[ERROR]
```

**Comment by agabrys** [comment]
This is an issue on my side. I will fix it in this week.

**Comment by agabrys** [comment]
[#62 Does not support star hack of IE7](https://sourceforge.net/p/cssparser/bugs/62/)

**Comment by agabrys** [comment]
The error is generated when you put ''@page`` rule inside ``@media`` query:

    @media all {
        @page {
            maring: 2px;
        }
    }

This is not a correct CSS code (see [CSS Validation Service](http://jigsaw.w3.org/css-validator/)).

I can add support for this, but I am not 100% sure, reasons:

* [CSS Parser](http://cssparser.sourceforge.net/) parses incorrect code. When author change/fix it, then my patch will stop working.
* Do you want to keep incorrect CSS code?

**Comment by philipjohn007** [comment]
Yeah.. I think providing a support would be helpful.

**Comment by agabrys** [comment]
Ok, I created a ticket: #9 
Please rest of the conversation about the ``@page`` inside ``@media`` to continue in that thread.

**Comment by agabrys** [comment]
I removed this issue from [1.0 milestone](https://github.com/gabrysbiz/css-splitter-maven-plugin/milestones/1.0), because it is blocked by third-party library. If author will fix it, then you can always override used version:

    <plugin>
        <groupId>biz.gabrys.maven.plugins</groupId>
        <artifactId>css-splitter-maven-plugin</artifactId>
        <version>used-version (e.g. 1.0)</version>
        <dependencies>
            <dependency>
                <groupId>net.sourceforge.cssparser</groupId>
                <artifactId>cssparser</artifactId>
                <version>version-with-patch</version>
            </dependency>
        </dependencies>
        ...
    </plugin>

Of course I will always release this plugin with the latest stable [CSS Parser](http://cssparser.sourceforge.net/) stable version.

**Comment by agabrys** [comment]
@philipjohn007 you can test 1.2.0-SNAPSHOT. For now fix works only with CSS 2.1 and 3.0 standards (3.0 is a default).

**Comment by agabrys** [comment]
You have to set `starHackAllowed` to true.

```
<plugin>
    <groupId>biz.gabrys.maven.plugins</groupId>
    <artifactId>css-splitter-maven-plugin</artifactId>
    <version>1.2.0-SNAPSHOT</version>
    <configuration>
        <starHackAllowed>true</starHackAllowed>
        ...
    </configuration>
</plugin>
```

**Comment by agabrys** [comment]
It will work only for CSS 2.1 and CSS 3.0 (http://cssparser.sourceforge.net/changes-report.html#a0.9.21).
